apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fraud-detection-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  groups:
  - name: fraud-detection.rules
    rules:
    - alert: FraudServiceDown
      expr: up{job="fraud-detection-service"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Fraud Detection Service is DOWN"
        description: "Fraud detection pod is not responding"
